name: front

on:
  push:
    branches: [ main ]
    paths:
      - 'public/**'
      - '.github/workflows/front.yml'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_FRONT_BUCKET: ${{ secrets.S3_FRONT_BUCKET }}
  CF_DIST_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync public/ to S3
        run: |
          if [ ! -d "public" ]; then
            echo "Pasta public/ não encontrada. Nada a publicar."
            exit 1
          fi
          aws s3 sync public/ "s3://${S3_FRONT_BUCKET}" --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${CF_DIST_ID}" \
            --paths "/*"
